services:
  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    container_name: nestjs-app
    restart: always
    command: npm run start:dev
    env_file:
      - ./.env
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nestjs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
